---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sparkcode/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R jQuery $DEPLOYPATH